name: Enforce merging to `main` from `develop`

on:
  pull_request:
    branches: 'main'

jobs:
  check_merge_from_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge from develop
        if: github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to `main` from `develop`."
          exit 1
