name: Enforce merging to `main` from `develop`

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  check_merge_from_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge from develop
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to \`main\` from \`develop\`."
          exit 1
